name: deploy to container instances

on:
    workflow_dispatch:
    pull_request:
      branches:
        - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Log in with Azure
            uses: azure/login@v1
            with:
              creds: '${{ secrets.AZURE_CREDENTIALS }}'

          - name: 'Build and push image'
            uses: azure/docker-login@v1
            with:
              login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
              username: ${{ secrets.REGISTRY_USERNAME }}
          - run: |
              docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleapp:${{ github.sha }}
              docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleapp:${{ github.sha }}
